# -*- coding: utf-8 -*-
"""googlemap_api.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16JSO_95HaRuLVFv26qhA16KAH8kQCUKT

Validate API Keys workable


*   Personal API Key=AIzaSyDOKVzBruT20_ap70kLzQsTmOe3vBIZv9s

# 1. Map JavaScript API : HTML Web

#2. Distance API
"""

import requests

url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=Washington%2C%20DC&destinations=New%20York%20City%2C%20NY&units=imperial&key=AIzaSyDOKVzBruT20_ap70kLzQsTmOe3vBIZv9s"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print("Distance API:", response.text)

"""#3. Directions API"""

import requests

url = "https://maps.googleapis.com/maps/api/directions/json?origin=台積電五廠&destination=張忠謀大樓&key=AIzaSyDOKVzBruT20_ap70kLzQsTmOe3vBIZv9s"

payload={}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print("Directions API:", response.text)

